wavefrontHQ/help

onboarding/next_steps.md
Invite users is optional and will not be displayed for everyone.
=> Remove invite users title

cloud_integrations_add_kubernetes.md, index.json
Adding some help contents is easier than removing the Help button from the page. So here it is. Feel free to modify my PR directly if you want to change anything.
=> Add Kubernetes setup help markdown

application_status.md, index.json, offline_traces.md, traces_browser.md
Add three new files to add help content for the following traces pages:
- Application status
- Traces browser
- Offline traces
=> Add help content for the tracing pages.

alerts_links.md, application_configuration.md, application_status.md, index.json, offline_traces.md, traces_browser.md
- Update the doc links for the tracing help pages
- Added a new page for the application configurations.
=> Update tracing links and add app config page

index.json
=> Tracing help

application_status.md
Change Tracing to Traces Browser and fix minor typo.
=> Change Tracing to Traces Browser and fix minor typo.

application_configuration.md, index.json, tracing_manage_sampling_policy.md, tracing_sampling_policy.md
- add the .md files
- update the index.json file
=> Add the help the help the help text for sampling policy

settings_profile.md, system_prefs.md
Made some fixes -- tab naming and permission naming. Included information about PromQL, fixed a broken link.
=> making some fixes to the docs

settings_profile.md, system_prefs.md
Trying to shorten the help topics a bit.
=> Trying to make these a bit shorter

system_prefs.md
Shortening text a little bit more.
=> Minor change

index.json, security_prefs.md, system_prefs.md
Trying to split the information of the Organization settings help topic into two topics displayed per tab.
=> trying to split the info into  two help topics.

apiaccess_profile.md, index.json, security_prefs.md, settings_profile.md, usegroups_profile.md
Split another help page into thee pages (tab-specific).
=> Splitting help pages.

apiaccess_profile.md, settings_permissions.md, settings_profile.md, system_prefs.md
=> Minor updates

system_prefs.md
=> Shortening text

cloud_integrations_add_amazon.md, cloud_integrations_add_vrops.md, index.json
Added a help doc for vRops and fixed a title.
=> vROps help topic

cloud_integrations_add_vrops.md
Added examples to the vROps help topic for fetching metrics.
=> Added examples

cloud_integrations_add_vrops.md
=> Shortening the text

cloud_integrations_add_vrops.md
Fixing the code of the OLH to HTML
=> OLH fix to get the docs site published as it has to be.

event_create.md, events_intro.md, events_links.md, external_link_create.md, external_links_links.md, metrics_links.md, next_steps.md, offline_traces.md, proxies_links.md, proxy_first_add.md, security_prefs.md, settings_permissions.md, settings_profile.md, settings_service_accounts.md, settings_users.md, sources_links.md, super_admin.md, system_prefs.md, tags.md, traces_browser.md, tracing_manage_sampling_policy.md, tracing_sampling_policy.md, user_groups.md, usergroups_profile.md, webhooks_links.md
added video links, removed images, changed "more info" to "read more"
=> Mariela video links

index.json
Adding the new alertsv1 path to the alert_create file.
=> Adding the alertsv1 path to the file.

cloud_integrations_add_vrops.md
Added Cloud to the vROps integration name.
=> Fix to the vROps Int name

cloud_integrations_add_vrops.md
=> Changes to the vROPs help topic wording

cloud_integrations_add_azure.md, cloud_integrations_add_vrops.md
The content of these help topics is also pulled in the docs site.
=> Minor fixes to the wording 

cloud_integrations_add_azure.md, cloud_integrations_add_vrops.md
Improving the help topics so that we show better information both in the help and in the docs site.
=> Improving help/doc.

cloud_integrations_add_snowflake.md, index.json
=> Snowflake doc

add_dynatrace.md, cloud_integrations_add_dynatrace.md, index.json
Dynatrace docs - 2 pages in the repo
=> Dynatrace docs

settings_query_dashboard.md
Minor fixes to the Slow queries dashboard help page
=> Minor fixes

cloud_integrations_add.md, cloud_integrations_add_aws.md, index.json
Reverting all changes from today.
=> Reverting changes.

cloud_integrations_add_amazon.md, cloud_integrations_add_aws.md, cloud_integrations_add_gcp.md, cloud_integrations_intro.md, index.json
Cherry picking some of my help improvements without adding the new .md files. Tested the help on an internal cluster.
Will add the new doc pages with another commit.
=> AWS and GCP doc/help improvements

apiaccess_profile.md, settings_permissions.md, system_prefs.md, tags.md
=> Added lines between the links

cloud_integrations_add_azure.md, cloud_integrations_add_gcp.md
Improved code and made some fixes
=> Minor fixes to the code

cloud_integrations_add_gcp.md, cloud_integrations_links.md, dashboard_links.md, dashboards_intro.md, dashboards_intro_v2.md, dashboards_links.md, dashboards_links_v2.md, events_intro.md, getting_started.md, metrics_links.md, proxies_intro.md, settings_permissions.md, settings_preferences.md, sources_intro.md, super_admin.md
Went through all links and made some fixes to improve experience.
=> help fixes

cloud_integrations_add_azure.md, cloud_integrations_add_gcp.md, cloud_integrations_edit_azure.md, cloud_integrations_edit_gcp_billing.md, cloud_integrations_edit_gcp_metrics.md, index.json
Improved help experience - new help docs for editing GCP/Azure + minor linguistic edits of the existing content.
=> Doc improvements

cloud_integrations_add_snowflake.md
Merge with master for the upcoming release.
=> Merging for the upcoming release

next_steps.md
=> Fix a link

cloud_integrations_add_cloudwatch.md, cloud_integrations_edit_cloudwatch.md
Add description about the CloudWatch bucket name allow list,
=> Mstaneva cloud watch bucket

add_kubernetes.md, cloud_integrations_add_kubernetes.md
Changes related to the K8s UI.
=> K8s UI-related changes

webhooks_intro.md
Small update to the page, will publish when we enable the feature to all clusters.
=> Small update to the alert targets help page

add_dynatrace.md, add_kubernetes.md, add_newrelic.md, cloud_integrations_add_aws.md, cloud_integrations_add_azure.md, cloud_integrations_add_gcp.md, cloud_integrations_add_snowflake.md, cloud_integrations_add_vrops.md
Merging the doc pages used by the script.
=> Mst rebranding

cloud_integrations_add_aws.md
Minor changes to the wording -- please review.
=> Minor changes to the wording

cloud_integrations_add_azure.md, cloud_integrations_add_gcp.md
=> Added info in the azure docs as well, removed an unnecessary punct. mark

add_gcp.md, cloud_integrations_add_gcp.md
=> Enable histogram metrics on GCP

add_kubernetes.md, cloud_integrations_add_kubernetes.md
This is supposed to go out with 195 but the doc is ready.
=> K8s changes related to CSP and Logs GA

alerts_intro.md
=> Minnor fix

onboarding_v2/csp_next_steps.md, onboarding_v2/welcome.md
Updated the link to the new support portal.
=> Fix support portal links
